import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public class StudentPanel extends JPanel {
    private final Connection conn;
    private JTable studentTable;

    public StudentPanel(Connection conn) {
        this.conn = conn;
        initializeUI();
    }

    private void initializeUI() {
        setLayout(new BorderLayout());

        // Add Student Form
        JPanel formPanel = new JPanel(new GridLayout(0, 2));
        JTextField nameField = new JTextField();
        JTextField emailField = new JTextField();
        JButton addButton = new JButton("Add Student");

        formPanel.add(new JLabel("Name:"));
        formPanel.add(nameField);
        formPanel.add(new JLabel("Email:"));
        formPanel.add(emailField);
        formPanel.add(addButton);

        // Student Table
        studentTable = new JTable();
        refreshTable();

        add(formPanel, BorderLayout.NORTH);
        add(new JScrollPane(studentTable), BorderLayout.CENTER);


        addButton.addActionListener(e -> {
            String name = nameField.getText();
            String email = emailField.getText();

            if (name.isEmpty() || email.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Name and email cannot be empty!");
                return;
            }

            // Insert student (ID is auto-generated by the database)
            new Insert(conn).insertStudent(name, email);
            refreshTable();
            nameField.setText("");
            emailField.setText("");
        });
    }

    // Fetch data from the database and populate the table
    private void refreshTable() {
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Name", "Email"}, 0);
        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM Students")) {
            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getInt("student_id"),
                        rs.getString("name"),
                        rs.getString("email")
                });
            }
            studentTable.setModel(model);
        } catch (Exception e) {
            System.out.println("Error loading students: " + e.getMessage());
        }
    }
}